FROM php:8.3.2RC1-fpm-alpine3.19
LABEL maintainer="blackaay@foxmail.com"
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk add --no-cache openssl-dev build-base autoconf \
    && pecl install swoole-5.1.1 \
    && echo 'extension=swoole.so' > /usr/local/etc/php/php.ini
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions bcmath calendar exif ftp gd gettext mongodb mysqli pcntl pdo_mysql redis shmop sockets sysvmsg sysvsem sysvshm xhprof xlswriter opcache zip xdebug
COPY ./php-fpm.d/zz-docker.conf /usr/local/etc/php-fpm.d/zz-docker.conf
RUN set -xe \
    && apk add --no-cache nginx supervisor\
    && mkdir -p /etc/supervisor/conf.d
